---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    source_code: embed
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(shiny)
library(flexdashboard)
library(viridis)
library(plotly)
```

````{r}
#Loading and tidying datasets

Edu_Employ_09 = 
  read.csv("./data/2009_Edu_Employ.csv") %>%
  janitor::clean_names() %>%
  rename(
    state = geo_display_label, 
    total_employ = hc01_est_vc01, 
    employ_ratio = hc03_est_vc01, 
    total_edu = hc01_est_vc31
    ) %>%
  select(
    state, 
    total_employ, 
    total_edu
  ) %>% 
  mutate(
    year = 2009, 
    state = recode(state, "Arkansas" = "AK", "Alabama" = "AL", "Alaska" = "AK", "Arizona" = "AZ", "California" = "CA", "Colorado" = "CO", "Connecticut" = "CT", "Delaware" = "DE", "Florida" = "FL", "Georgia" = "GA", "Hawaii" = "HI", "Idaho" = "ID", "Illinois" = "ID", "Indiana" = "IN", "Iowa" = "IA", "Kansas" = "KS", "Kentucky" = "KY", "Louisiana" = "LA", "Maine" = "ME", "Maryland" = "MD", "Massachusetts" = "MA", "Michigan" = "MI", "Minnesota" = "MN", "Mississippi" = "MS", "Missouri" = "MO", "Montana" = "MT", "Nebraska" = "NE", "Nevada" = "NV", "New Hampshire" = "NH", "New Jersey" = "NJ", "New Mexico" = "NM", "New York" = "NY", "North Carolina" = "NC", "North Dakota" = "ND", "Ohio" = "OH", "Oklahoma" = "OK", "Oregon" = "OR", "Pennsylvania" = "PA", "Rhode Island" = "RI", "South Carolina" = "SC", "South Dakota" = "SD", "Tennessee" = "TN", "Texas" = "TX", "Utah" = "UT", "Vermont" = "VT", "Virginia" = "VA", "Washington" = "WA", "West Virginia" = "WV", "Wisconsin" = "WI", "Wyoming" = "WY"))
  
Edu_Employ_09 =   
  Edu_Employ_09[-c(52),]

Edu_Employ_09 = 
  Edu_Employ_09[-c(9),]

  

Edu_Employ_17 = 
  read.csv("./data/2017_Edu_Employ.csv") %>%
  janitor::clean_names() %>%
  rename(
    state = geo_display_label, 
    total_employ = hc01_est_vc01, 
    employ_ratio = hc03_est_vc01, 
    total_edu = hc01_est_vc43
    ) %>%
  select(
    state, total_employ, total_edu
  ) %>%
mutate (
  year = 2017,
  state = recode(state, "Arkansas" = "AK", "Alabama" = "AL", "Alaska" = "AK", "Arizona" = "AZ", "California" = "CA", "Colorado" = "CO", "Connecticut" = "CT", "Delaware" = "DE", "Florida" = "FL", "Georgia" = "GA", "Hawaii" = "HI", "Idaho" = "ID", "Illinois" = "ID", "Indiana" = "IN", "Iowa" = "IA", "Kansas" = "KS", "Kentucky" = "KY", "Louisiana" = "LA", "Maine" = "ME", "Maryland" = "MD", "Massachusetts" = "MA", "Michigan" = "MI", "Minnesota" = "MN", "Mississippi" = "MS", "Missouri" = "MO", "Montana" = "MT", "Nebraska" = "NE", "Nevada" = "NV", "New Hampshire" = "NH", "New Jersey" = "NJ", "New Mexico" = "NM", "New York" = "NY", "North Carolina" = "NC", "North Dakota" = "ND", "Ohio" = "OH", "Oklahoma" = "OK", "Oregon" = "OR", "Pennsylvania" = "PA", "Rhode Island" = "RI", "South Carolina" = "SC", "South Dakota" = "SD", "Tennessee" = "TN", "Texas" = "TX", "Utah" = "UT", "Vermont" = "VT", "Virginia" = "VA", "Washington" = "WA", "West Virginia" = "WV", "Wisconsin" = "WI", "Wyoming" = "WY"))

Edu_Employ_17 = 
  Edu_Employ_17 [-c(1),] 

Edu_Employ_17 = 
  Edu_Employ_17[-c(53),]

Edu_Employ_17 = 
  Edu_Employ_17[-c(10),]

  
Homelessness = 
  read.csv("./data/us_homelessness_07_18.csv") %>%
  select(state, year, total_homeless)
```

```{r}
#Merging datasets 
Edu_Employ = rbind(Edu_Employ_09, Edu_Employ_17)
  
HEE_merged = 
  inner_join(Homelessness, Edu_Employ) %>%
  mutate(
    total_homeless = as.numeric(total_homeless), 
    total_employ = as.numeric(total_employ), 
    total_edu = as.numeric(total_edu)
  ) %>%
  pivot_longer(
    total_homeless:total_edu,
    names_to = "covariates",
    values_to = "stats"
  ) %>%
  mutate(
    covariates = case_when(
      covariates == "total_homeless" ~ "Homeless",
      covariates == "total_employ" ~"Employment",
      covariates == "total_edu" ~ "Education"
    )
  )

```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
#Creating years list
covariates = 
  HEE_merged %>%
  distinct(covariates) %>%
  pull()


#Creating input for years
numericInput(
  "year_choice",
  label = h4("Select year (2009-2017)"),
  min = 2009,
  max = 2017,
  value = 2017,
  step = 8
  )

radioButtons(
  "covariates_type",
  label = h4("Select covariate"),
  choices = covariates,
  selected = "Homeless"
  )
```

Column {.tabset}
-----------------------------------------------------------------------

### Homelessness and Education and Employment in US by State

```{r}
##Creating interactive map

renderPlotly({
	geo1 = list(
	  scope = "usa",
	  projection = list(type = "albers usa"),
	  lakecolor = toRGB("white")
	)


HEE_merged %>% 
  mutate(state_name = openintro::abbr2state(state)) %>% 
	filter(year == input[["year_choice"]], covariates == input[["covariates_type"]]) %>% 
  plot_geo(locationmode = "USA-states") %>% 
	add_trace(
		z = ~stats,
		locations = ~state,
		text = ~paste(covariates, state_name, sep = "\n"),
		color = ~stats,
		colors = "Greens"
		) %>%
    colorbar(title = input[["covariates_type"]]) %>%
	layout(
		geo = geo1,
		title = "Homelessness, Education, and Employment in the United States")
})
```
